# Default values for app-mono-www.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: infracloud/app-mono-www
  tag: 9f7b43b
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

env:
  API_URL: app-mono-api:80
  LOG_LEVEL: debug
  SHUD_LOG_TO_FILE: false
  WWW_PORT: 8081
